### ISSUE TITLE
AngularJS not defined

### ISSUE THREAD

**Issue by madhabnath** [googledrive/web-quickeditor#2]
When I tried to run the code after installing it as per the steps mentioned, I got the following error -

![error](https://cloud.githubusercontent.com/assets/16030963/11836521/3eee9c54-a401-11e5-8b12-83a9f998f080.png)

Can anyone tell me what is the issue here?

**Comment by inlinecoder** [comment]
@madhabnath , make sure you have update `gulp-ng-annoate` in `package.json` to the most recent version. Then `gulp build` and then open `/dist/index.html` and everything should work.

Let me know if it fixes the issues for you.

**Comment by inlinecoder** [comment]
@madhabnath for me, updating 2 dependencies made things going... 
<img width="442" alt="screen shot 2017-04-13 at 06 03 49" src="https://cloud.githubusercontent.com/assets/4806743/24988494/fbf36cdc-200e-11e7-8702-73e3e43021d5.png">

**Comment by sqrrrl** [comment]
Just updated all the dependencies and simplified the build steps, should be OK now.
