### ISSUE TITLE
I am getting following install error

### ISSUE THREAD

**Issue by Rohan-Jalil** [googledrive/web-quickeditor#3]
![editor-error](https://cloud.githubusercontent.com/assets/1014750/24098319/b5208992-0d8b-11e7-8506-22bec5db77df.png)

**Comment by inlinecoder** [comment]
+1.
Same shit here.

**Comment by inlinecoder** [comment]
@Rohan-Jalil , update `package.json`, `gulp-sass` to, say, version 3.1.0 (the latest one), and it should work.

**Comment by sqrrrl** [comment]
Just updated all the dependencies and simplified the build steps, should be OK now.
